services:
  - type: web
    name: maze-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r MazeGeneration/requirements.txt
    startCommand: python MazeGeneration/mazeAPI.py
